import { Inter, Roboto_Slab, Poppins } from 'next/font/google'
import './globals.css'

// Configuración de la fuente principal (Inter)
const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter', // Asigna a una variable CSS
  display: 'swap',
})

// Configuración de la fuente Roboto Slab
const roboto_slab = Roboto_Slab({
  subsets: ['latin'],
  weight: ['400', '700'], // Carga los grosores que usaremos
  variable: '--font-roboto-slab', // Asigna a una variable CSS
  display: 'swap',
})

// Configuración de la fuente Poppins
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '900'], // Carga los grosores que usaremos
  variable: '--font-poppins', // Asigna a una variable CSS
  display: 'swap',
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      {/* Combinamos las clases de las fuentes en el body */}
      <body className={`${inter.variable} ${roboto_slab.variable} ${poppins.variable} font-sans bg-slate-100`}>
        {children}
      </body>
    </html>
  )
}